name: remote
description: "Untitled USV remote controller. "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  logger: ^2.5.0
  permission_handler: ^12.0.0+1
  udp: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  background_color: "#ffffff"